import { execSync } from 'node:child_process';
import { promises as fs } from 'node:fs';

const pkg = JSON.parse(await fs.readFile('package.json', 'utf8'));
const version = pkg.version ?? '0.0.0';

function safeExec(cmd) {
  try {
    return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return '';
  }
}

const commit =
  process.env.COMMIT_REF ??
  process.env.GITHUB_SHA ??
  safeExec('git rev-parse HEAD');

const shortCommit = (commit || '').slice(0, 7) || 'dev';

const url = pkg.repository?.url
  ? pkg.repository.url.replace(/^git\+/, '').replace(/\.git$/, '')
  : 'https://github.com/cafeinadesign/karaoke-live';

const content = `// Generated by scripts/gen-version.mjs — do not edit.
export const APP_VERSION = ${JSON.stringify(version)};
export const APP_COMMIT = ${JSON.stringify(shortCommit)};
export const APP_REPO_URL = ${JSON.stringify(url)};
export const APP_COMMIT_URL = ${JSON.stringify(
  shortCommit && shortCommit !== 'dev' ? `${url}/commit/${commit}` : url,
)};
`;

await fs.writeFile('src/version.generated.ts', content);
console.log(`✓ version ${version} @ ${shortCommit}`);
